name: Deploy Terraform Infrastructure - STAGING

on: 
#   push:
#     branches:
#       - main
#     paths:
#       - 'terraform/environments/staging/**'
#       - '.github/workflows/deploy-staging.yml'

  workflow_dispatch:

env:
  ENVIRONMENT: staging
  TF_DIR: terraform/environments/staging

jobs:
  terraform-plan:
    name: Terraform Plan (STAGING)
    runs-on: ubuntu-latest
    environment:
      name: staging 
    defaults:
      run:
        working-directory: ${{ env.TF_DIR }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file="terraform.tfvars"

  terraform-apply:
    name: Terraform Apply (STAGE)
    needs: terraform-plan
    if: success()
    runs-on: ubuntu-latest
    environment:
      name: staging

    defaults:
      run:
        working-directory: ${{ env.TF_DIR }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
