name: Build and Deploy to Azure App Service

on:
#   push:
#     branches:
#       - main

  workflow_dispatch:
env:
  ACR_SERVER_NAME: acrawaresondev
  APP_SERVICE_NAME: app-awareson-dev
  RESOURCE_GROUP: awareson-dev-plc-rg

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    environment:
      name: dev 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set image tag to commit SHA
        id: vars
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to ACR
        run: |
          az acr login --name ${{ env.ACR_SERVER_NAME }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.ACR_SERVER_NAME }}.azurecr.io/myapp-${{ env.IMAGE_TAG }} .
  
      - name: Push Docker image to ACR
        run: |
          docker push ${{ env.ACR_SERVER_NAME }}.azurecr.io/myapp-${{ env.IMAGE_TAG }}
  
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_SERVICE_NAME }}
          images: ${{ env.ACR_SERVER_NAME }}.azurecr.io/myapp-${{ env.IMAGE_TAG }}
          resource-group-name: ${{ env.RESOURCE_GROUP }}
