name: Build & Publish App

on:
  workflow_dispatch:

env:
  ACR_SERVER_NAME: acrawaresondev
  APP_SERVICE_NAME: app-awareson-dev
  RESOURCE_GROUP: awareson-dev-plc-rg
  KEYVAULT_NAME: kv-awareson-dev
  DB_NAME: db1
  DB_SERVER: sql-awareson-dev.database.windows.net
  IMAGE NAME: myapp
  IMAGE_TAG: ${{ github.sha }}

jobs:
  db-test:
    runs-on: ubuntu-latest
    environment: dev
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
      - uses: actions/checkout@v3    
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get DB secrets from Key Vault
        uses: azure/get-keyvault-secrets@v1
        with:
            keyvault: ${{ env.KEYVAULT_NAME }}
            secrets: 'sql-server-admin-username, sql-server-admin-password'

    #   - name: Get secrets from Azure Key Vault
    #     run: |
    #       echo "DB_USER=$(az keyvault secret show --vault-name ${{ env.KEYVAULT_NAME }} --name sql-server-admin-username --query value -o tsv)" >> $GITHUB_ENV
    #       echo "DB_PASSWORD=$(az keyvault secret show --vault-name ${{ env.KEYVAULT_NAME }} --name sql-server-admin-password --query value -o tsv)" >> $GITHUB_ENV

      - name: Install mssql package locally
        run: npm install mssql

      - name: Run DB connection test
        run: node scripts/test-db-connection.js
        env: 
          DB_USER: ${{ env.sql-server-admin-username }}
          DB_PASSWORD: ${{ env.sql-server-admin-password }}
          DB_SERVER: ${{ env.DB_SERVER }}
          DB_NAME: ${{ env.DB_NAME }}


  build-push:
    runs-on: ubuntu-latest
    environment: dev
    needs: db-test
    steps:
      - uses: actions/checkout@v3
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name ${{ env.ACR_SERVER_NAME }}

      - name: Build Docker image
        run: docker build -t ${{ env.ACR_SERVER_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ./app

      - name: Push Docker image to ACR
        run: docker push ${{ env.ACR_SERVER_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    needs: build-push
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_SERVICE_NAME }}
          images: ${{ env.ACR_SERVER_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          resource-group-name: ${{ env.RESOURCE_GROUP }}